apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.consulConfigMapName }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ .Values.name }}
data:
  # When the config map is mounted as a volume, these will be created as files.
  client.vancouver.json: {{ .Values.consul_client_conf | quote }}
  server.vancouver.json: {{ .Values.consul_server_conf | quote }}
