apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name  }}
  labels:
    app: {{ .Values.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  type: {{ .Values.service.type }}
  ports:
      {{range .Values.consulPorts}}
    - port: {{ .value }}
      targetPort: {{ .value }}
      protocol: TCP
      name: {{ .name }}
      {{- end}}
      {{range .Values.servicePorts}}
    - port: {{ .value }}
      targetPort: {{ .value }}
      protocol: TCP
      name: {{ .name }}
      {{- end}}
  selector:
    app: {{ .Values.name }}
